altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  de73660b-faa6-4d00-b0fd-cb2a738a8fd5:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-13T21:03:52+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 5cb4c1dc-d76d-43da-b30d-572ce70bfefa
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2025-10-13T21:46:32+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: true
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: c6491ae4-a8b8-4b97-be58-d367d0e8f229
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 11fdf782-c8c7-4566-8dec-4cffa57078b4
        userCondition: null
fs: local
handle: mainImages
name: 'Main Images'
sortOrder: 1
subpath: main-images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
