color: null
description: null
fieldLayouts:
  feefc7d7-6a38-4ff0-885c-a5c7a998be77:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-21T21:25:51+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Series Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 042cae0d-18fa-4f7c-9d97-84b7406aee14
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-10T22:36:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d468b09c-d9d5-4249-85c2-742dcb0fb4d5 # Post Summary
            handle: null
            includeInCards: false
            instructions: null
            label: 'Series Summary'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7082570-fee7-4aae-8405-da48a3273ca8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-10T22:41:40+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 90f462df-4bab-488f-982f-f28421852073 # Social Preview Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 031f3f56-8b47-4c44-a65f-448313e5b458
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ff4a35c6-6787-4140-8c86-c35cdf11e160
        userCondition: null
handle: blogSeries
hasTitleField: true
icon: null
name: 'Blog Series'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
