defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 7f558239-c72e-42a3-963e-4e32291ef801 # Blog
handle: blog
maxAuthors: 1
name: Blog
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  eb73adb8-d528-42a2-a6ec-9d15818070e7: # kristengrote.com
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry.twig
    uriFormat: 'blog/{slug}'
type: channel
