dateModified: 1724621233
email:
  fromEmail: kristen@kristengrote.com
  fromName: kristengrote.com
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    d913d357-03f1-41f2-a6da-a04afb082c6f: kristengrote.com # kristengrote.com
    eb73adb8-d528-42a2-a6ec-9d15818070e7: kristengrote.com # kristengrote.com
system:
  edition: solo
  live: true
  name: kristengrote.com
  schemaVersion: 5.3.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
